name: calendar_mgmt_services_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_ce: ^2.10.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  dio: ^5.8.0+1
  intl: ^0.20.2
  geolocator: ^13.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/locations.json
    - lib/assets/ISO_3166.json
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
